name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  linting:
    name: "Linting (swift-format)"
    runs-on: macos-15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install swift-format
        run: brew install swift-format

      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log

  test-darwin:
    name: "Test (on ${{ matrix.platform.name }})"
    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'macOS', grep: 'macOS' }
          - { name: 'iOS', grep: 'iPhone' }
          - { name: 'tvOS', grep: 'Apple TV' }
          - { name: 'watchOS', grep: 'Apple Watch' }
          - { name: 'visionOS', grep: 'Apple Vision' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build and run tests
        run: |
          PLATFORM_NAME="${{ matrix.platform.name }}"
          if [[ "$PLATFORM_NAME" == "macOS" ]]; then
            xcodebuild test -scheme ya-swift-html-xml-parser -destination "platform=macOS,arch=arm64"
          else
            GREP_PATTERN="${{ matrix.platform.grep }}"
            UDID=$(xcrun simctl list devices available | grep -m 1 "$GREP_PATTERN" | awk 'match($0, /\(([-0-9A-F]+)\)/) { print substr($0, RSTART + 1, RLENGTH - 2) }')
            
            if [ -z "$UDID" ]; then
              echo "::error::Could not find an available simulator for ${PLATFORM_NAME}"
              exit 1
            fi

            echo "Found available ${PLATFORM_NAME} simulator with UDID: ${UDID}"
            
            xcodebuild test -scheme ya-swift-html-xml-parser -destination "platform=${PLATFORM_NAME} Simulator,id=${UDID}"
          fi

  test-darwin-beta:
    name: "Test (Xcode 26 Beta on macOS)"
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 26.0
        run: sudo xcode-select -s /Applications/Xcode_26.0.app

      - name: Build and run tests
        run: xcodebuild test -scheme ya-swift-html-xml-parser -destination "platform=macOS,arch=arm64"

  test-linux-stable:
    name: "Test (Swift 6.1 on Ubuntu 24.04 LTS)"
    runs-on: ubuntu-latest
    container: 'swift:6.1.2-noble'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install libxml2
        run: apt-get update && apt-get install -y libxml2-dev

      - name: Build and run tests
        run: swift test

  test-linux-nightly:
    name: "Test (Swift 6.2 Nightly on Ubuntu 24.04 LTS)"
    runs-on: ubuntu-latest
    container: 'swiftlang/swift:nightly-6.2-noble'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install libxml2
        run: apt-get update && apt-get install -y libxml2-dev

      - name: Build and run tests
        run: swift test
  
  test-android:
    name: "Test (Swift 6.1 on Android)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Test Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.1
